import pandas as pd
import os

def parquet_to_csv(parquet_file_path: str, csv_file_path: str = None, **kwargs):
    """
    Converts a Parquet file to a CSV file using the pandas library.

    Args:
        parquet_file_path (str): The full path to the input Parquet file.
        csv_file_path (str, optional): The full path for the output CSV file. 
                                        If None, the output path is generated by 
                                        replacing '.parquet' with '.csv' in the input path.
        **kwargs: Optional keyword arguments passed directly to the pandas to_csv() function,
                  such as 'sep', 'index', 'encoding', etc.

    Returns:
        str: The path to the newly created CSV file.

    Raises:
        FileNotFoundError: If the specified Parquet file does not exist.
        Exception: For any other errors during the conversion process.
    """
    
    if not os.path.exists(parquet_file_path):
        raise FileNotFoundError(f"Error: Parquet file not found at '{parquet_file_path}'")
        
    # Determine the output path if not explicitly provided
    if csv_file_path is None:
        base, _ = os.path.splitext(parquet_file_path)
        csv_file_path = base + '.csv'
        
    print(f"Reading Parquet file: {parquet_file_path}")
    try:
        # Read the Parquet file into a pandas DataFrame
        df = pd.read_parquet(parquet_file_path)
        
        # Write the DataFrame to a CSV file
        df.to_csv(csv_file_path, **kwargs)
        
        print(f"Successfully converted and saved to CSV file: {csv_file_path}")
        return csv_file_path
        
    except Exception as e:
        print(f"An error occurred during conversion: {e}")
        # Re-raise the exception to be handled by the caller
        raise


def edit_parquet_counts(input_filepath: str, output_filepath: str):
    """
    Reads a single-row Parquet file and modifies the count in two specified nested columns.

    Args:
        input_filepath (str): Path to the input Parquet file.
        output_filepath (str): Path where the modified Parquet file will be saved.
    """
    
    # Define the target value and the columns to modify
    NEW_VALUE = [1454]
    COLUMNS_TO_EDIT = [
        'stats/observation.image.main/count',
        'stats/observation.image.rear/count'
    ]

    print(f"--- Starting modification process ---")
    print(f"Loading file: {input_filepath}")

    if not os.path.exists(input_filepath):
        print(f"Error: Input file not found at {input_filepath}")
        return

    try:
        # 1. Read the Parquet file
        df = pd.read_parquet(input_filepath)
        
        # Check if the DataFrame has exactly 1 row as expected
        if len(df) != 1:
            print(f"Warning: The Parquet file has {len(df)} rows, but the script is designed for 1 row. Modifying row 0.")

        # 2. Modify the values in the specified columns
        # We use .loc[0, col_name] to specifically target the first row (index 0)
        # and assign the new list value [1454].
        for col in COLUMNS_TO_EDIT:
            if col in df.columns:
                # Use .loc to ensure modification on the original DataFrame
                df.loc[0, col] = NEW_VALUE
                print(f"Modified column '{col}'. New value: {NEW_VALUE}")
            else:
                print(f"Warning: Column '{col}' not found in the DataFrame.")
                
        # 3. Save the modified DataFrame to the new output file
        df.to_parquet(output_filepath, index=False)
        
        print("-" * 40)
        print(f"Successfully saved modified data to: {output_filepath}")
        print("Final Data (Row 0):")
        print(df.iloc[0]) # Print the single modified row
        
    except Exception as e:
        print(f"An unexpected error occurred during processing: {e}")

# --- Execution Example ---
if __name__ == "__main__":
    # Define file paths
    INPUT_FILE = '/workspace/data/test_cams/10fps/meta/episodes/chunk-000/file-000.parquet'
    OUTPUT_FILE = '/workspace/data/test_cams/10fps/meta/episodes/chunk-000/file-001.parquet'
    
    # Step 2: Run the modification function
    #edit_parquet_counts(INPUT_FILE, OUTPUT_FILE)

    # Optional cleanup (comment out if you want to inspect the files)
    # os.remove(INPUT_FILE)
    # os.remove(OUTPUT_FILE)

    path = '/workspace/data/test_cams/hold/data/chunk-000/file-000.parquet'
    csv = '/workspace/data/test_cams/file-000.csv'
    parquet_to_csv(path, csv)
